### ISSUE TITLE
Make OND protocol a package

### ISSUE THREAD

**Issue by nrsyed** [tinker-engine/sailon-protocols#4]
The protocol currently uses hacks like changing `sys.path` to function within the Tinker engine framework and should be made into a pip-installable package.

**Comment by waxlamp** [comment]
Making it a package would be a good practical test for SMQTK's plugin search capabilities.

Do you have a path forward on this? How urgent do you think it is for the initial phase where we're prototyping and bootstrapping the "port" from the old codebase?

**Comment by nrsyed** [comment]
I'm working on it now and recently pushed a new branch to that end. Since the old code used a similar approach, I think this will facilitate prototyping/bootstrapping and reduce the amount of porting that needs to be done.
